### ISSUE TITLE
I'm using Windows 11. When adding good_lp to dependencies in Cargo.toml, I'm getting compilation errors related to 'CbcSolver.lib'.

### ISSUE THREAD

**Issue by GG-O-BP** [rust-or/good_lp#69]
```toml
[package]
name = "jgsm-rs"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "jgsm_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
scraper = "0.21.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = "1.41.1"
chrono = "0.4.38"
regex = "1.11.1"
once_cell = "1.20.2"
parking_lot = "0.12.3"
rayon = "1.10.0"
rand = "0.8.5"
good_lp = "1.10.0"
```

error: linking with `link.exe` failed: exit code: 1181
(various paths...)
  = note: LINK : fatal error LNK1181: 'CbcSolver.lib'

I'm having trouble finding information about this online, and even after installing cbc, I can't locate where the CbcSolver.lib file should be. It's difficult to find relevant documentation about this issue.

**Comment by Bubbler-4** [comment]
MRE:

* `Cargo.toml`

```toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[lib]
name = "scratch_lib"
crate-type = ["cdylib"]

[dependencies]
good_lp = "1.10.0"
```

* `lib.rs` (I had to code something that uses `good_lp` to trigger the error, so here is a simple LP problem)

```rust
use good_lp::{default_solver, variable, Expression, ProblemVariables, Solution, SolverModel};

pub fn example(n: usize) {
    let mut vars = vec![];
    let mut pvars = ProblemVariables::new();
    let mut sum = Expression::from_other_affine(0.);
    for i in 0..n {
        vars.push(pvars.add(variable().min(0).max(1)));
        sum += vars[i];
    }
    let mut solver = pvars.maximise(sum).using(default_solver);
    for w in vars.windows(3) {
        solver.add_constraint(w[0] + w[1] + w[2] << 1);
    }
    let solution = solver.solve().unwrap();
    for var in vars {
        println!("{}", solution.value(var));
    }
}
```

The error is only triggered when `crate_type` is `cdylib`. It builds fine with `rlib` and `staticlib`.
